WebQuery/Models/ErrorViewModel.cs
using System;

namespace WebQuery.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebQuery/Models/QueryOne.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebQuery.Models
{
    public class QueryOne
    {

		public string Pedido { get; set; }
		public string Fecha { get; set; }
		public string Cliente_Nit { get; set; }
		public string Cliente_Suc { get; set; }
		public string Cliente { get; set; }		
		public string Co_Id { get; set; }
		public string Centro_Operacion { get; set; }
		public string Bodega_Id { get; set; }
		public string Bodega { get; set; }
		public int Item_Id { get; set; }
		public string Item { get; set; }
		public string Unidad_Pedida { get; set; }
		public float Cantidad_Ped { get; set; }
		public string Estado { get; set; }
		public string Error { get; set; }
		

	}
}

WebQuery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebQuery.Models;

namespace WebQuery.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebQuery/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebQuery.DAO;
using WebQuery.Models;

namespace WebQuery.Controllers
{
    public class QueryController : Controller
    {
        SQLTransaction db;
        DataSet data;
        List<QueryOne> listData;

        public QueryController()
        {
            db = new SQLTransaction();
            data = db.GetData();
            listData = new List<QueryOne>();
            foreach (DataRow item in data.Tables[0].Rows)
            {
                listData.Add(new QueryOne
                {
                    Pedido = item["Pedido"].ToString(),
                    Fecha = item["Fecha"].ToString(),
                    Cliente_Nit = item["Cliente_Nit"].ToString(),
                    Cliente_Suc = item["Cliente_Suc"].ToString(),
                    Cliente = item["Cliente"].ToString(),
                    Co_Id = item["Co_Id"].ToString(),
                    Centro_Operacion = item["Centro_Operacion"].ToString(),
                    Bodega_Id = item["Bodega_Id"].ToString(),
                    Bodega = item["Bodega"].ToString(),
                    Item_Id = Convert.ToInt32(item["Item_Id"]),
                    Item = item["Item"].ToString(),
                    Unidad_Pedida = item["Unidad_Pedida"].ToString(),
                    Cantidad_Ped = Convert.ToInt32(item["Cantidad_Ped"]),
                    Estado = item["Estado"].ToString(),
                    Error = item["Error"].ToString()
                });
            }
        }
        public  IActionResult Index(string sortOrder,string currentFilter,string searchString, int? page)
        {
            
            ViewData["NombreSortParm"] = String.IsNullOrEmpty(sortOrder) ? "nombre_desc" : "";
            ViewData["DescripcionSortParm"] = sortOrder == "descripcion_asc" ? "descripcion_desc" : "descripcion_asc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentSort"] = sortOrder;
            

            //db = new SQLTransaction();
            //data = db.GetData();
            //List<QueryOne> listData = new List<QueryOne>();
            //foreach (DataRow item in data.Tables[0].Rows)
            //{
            //    listData.Add(new QueryOne
            //    {
            //        Pedido =item["Pedido"].ToString(),
            //        Fecha=item["Fecha"].ToString(),
            //        Cliente_Nit= item["Cliente_Nit"].ToString(),
            //        Cliente_Suc= item["Cliente_Suc"].ToString(),
            //        Cliente= item["Cliente"].ToString(),
            //        Co_Id= item["Co_Id"].ToString(),
            //        Centro_Operacion= item["Centro_Operacion"].ToString(),
            //        Bodega_Id = item["Bodega_Id"].ToString(),
            //        Bodega= item["Bodega"].ToString(),
            //        Item_Id = Convert.ToInt32(item["Item_Id"]),
            //        Item = item["Item"].ToString(),
            //        Unidad_Pedida=item["Unidad_Pedida"].ToString(),
            //        Cantidad_Ped = Convert.ToInt32(item["Cantidad_Ped"]),
            //        Estado=item["Estado"].ToString(),
            //        Error = item["Error"].ToString()
            //    }); 
            //}

            var querys = from s in listData select s;
            ViewData["Data"] = querys;
            if (!String.IsNullOrEmpty(searchString))
            {
                querys = querys.Where(s => s.Cliente.Contains(searchString) || s.Cliente_Nit.Contains(searchString) || s.Pedido.Contains(searchString) || s.Fecha.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "nombre_desc":
                    querys = querys.OrderByDescending(s => s.Pedido);
                    break;
                default:
                    querys = querys.OrderBy(s => s.Pedido);
                    break;
            }

            var queryfinal = querys.AsQueryable();
            int pageSize = 20;
            return View( Pag<QueryOne>.CreateAsync(queryfinal, page ?? 1,pageSize));

        }

        
    }
}

WebQuery/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebQuery/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebQuery/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

WebQuery/Views/Query/Index.cshtml
@model WebQuery.DAO.Pag<QueryOne>
@{
    ViewData["Title"] = "Resultado de Consulta";
}

<form asp-action="Index" method="get">
    <div class="form-action no-color">
        <p>
            Filtro: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Buscar" class="btn btn-default" onclick="process()" />
            <a asp-action="Index" onclick="process()">Todos los Registros</a> | Registros encontrados @Model.TotalR
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["NombreSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Pedido</a></th>
            <th>Fecha</th>
            <th>Nit Cliente</th>
            <th>Cliente Sucursal</th>
            <th>Cliente</th>
            <th>Id Centro Operacion</th>
            <th>Centro Operacion</th>
            <th>Id Bodega</th>
            <th>Bodega</th>
            <th>Id Item</th>
            <th>Item</th>
            <th>Unidad Pedida</th>
            <th>Cantidad Pedida</th>
            <th>Estado</th>
            <th>Error</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Pedido</td>
                <td>@item.Fecha</td>
                <td>@item.Cliente_Nit</td>
                <td>@item.Cliente_Suc</td>
                <td>@item.Cliente</td>
                <td>@item.Co_Id</td>
                <td>@item.Centro_Operacion</td>
                <td>@item.Bodega_Id</td>
                <td>@item.Bodega</td>
                <td>@item.Item_Id</td>
                <td>@item.Item</td>
                <td>@item.Unidad_Pedida</td>
                <td>@item.Cantidad_Ped</td>
                <td>@item.Estado</td>
                <td>@item.Error</td>
            </tr>
        }
    </tbody>

</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    var pageIndex = Model.PageIndex;
    var numberPage = "";
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex+1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   
   class="btn btn-default @prevDisabled"
   onclick="process()">
    Anterior
</a>
@for (int i = 1; i <= Model.TotalPages; i++)
{
    if (pageIndex == i)
    {
        numberPage = "disabled";
    }
    else
    {
        numberPage = "";
    }
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@i"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @numberPage"
       onclick="process()">
       @i
    </a>
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex+1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-dataView="@ViewData["Data"]"
   class="btn btn-default @nextDisabled"
   onclick="process()">
    Siguiente
</a>

WebQuery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebQuery</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <style>


        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            padding-top: 100px; /* Location of the box */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
        }

        .modalprocess-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 1px solid #888;
            width: 30%;
        }

        /* The Close Button */
        .close {
            /*color: #aaaaaa;*/
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

            .close:hover,
            .close:focus {
                color: #000;
                text-decoration: none;
                cursor: pointer;
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Query" asp-action="Index" class="navbar-brand" onclick="process()">WebQuery</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()

 
        <div id="process" class="modal">
            <!-- Modal content -->
            <div class="modalprocess-content">
                <div class="modal-body">
                    <div class="text-center">
                        <img src="../images/loading.gif" class="icon" />
                        <h5><span class="modal-text">Procesando, Espere por favor... </span></h5>
                    </div>
                </div>
            </div>

        </div>

        <hr />
        <footer>
            <p>&copy; 2019 - WebQuery</p>
        </footer>
    </div>


    <script>
        function process() {

            var process = document.getElementById('process');            
                process.style.display = "block";
            

        }
    </script>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>